# Generated by Django 3.2.15 on 2022-10-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('gpa', models.CharField(blank=True, max_length=255)),
                ('about', models.TextField(blank=True, max_length=1000)),
                ('start', models.CharField(blank=True, max_length=255)),
                ('end', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('about', models.TextField(blank=True, max_length=1000)),
                ('start', models.CharField(blank=True, max_length=255)),
                ('end', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InterestsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageToolsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_css_class', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('about', models.TextField(blank=True, max_length=1000)),
                ('start', models.CharField(blank=True, max_length=255)),
                ('end', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
