# Generated by Django 3.2.15 on 2022-10-31 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221031_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagetoolsmodel',
            old_name='fa_css_class',
            new_name='css_class',
        ),
    ]
