# Generated by Django 3.2.15 on 2022-10-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_fa_css_class_languagetoolsmodel_css_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='show_first',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='show_first',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='interestsmodel',
            name='show_first',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='languagetoolsmodel',
            name='show_first',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='show_first',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workflowmodel',
            name='show_first',
            field=models.IntegerField(default=1),
        ),
    ]
