# Generated by Django 4.1.3 on 2022-12-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221031_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagetoolsmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='photo',
            field=models.ImageField(blank=True, default='/main/static/assets/img/profile.jpg', null=True, upload_to='images/'),
        ),
    ]
