# Generated by Django 4.1.3 on 2022-12-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_languagetoolsmodel_name_alter_portfoliomodel_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagetoolsmodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
