# Generated by Django 4.1.3 on 2022-12-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projectmodel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OthersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('about', models.TextField(blank=True, max_length=1000)),
                ('show_first', models.IntegerField(default=1)),
                ('date', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
