# Generated by Django 4.1.3 on 2022-12-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_othersmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencemodel',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
