# Generated by Django 4.1.3 on 2022-12-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_experiencemodel_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagetoolsmodel',
            name='css_class',
        ),
    ]
