# Generated by Django 4.1.3 on 2022-12-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_languagetoolsmodel_css_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='website',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='github',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='linkedin',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='twitter',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
