# Generated by Django 4.1.3 on 2022-12-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_portfoliomodel_website_alter_portfoliomodel_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
