# Generated by Django 4.2.4 on 2024-04-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_portfoliomodel_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('by', models.CharField(blank=True, max_length=255)),
                ('link', models.CharField(blank=True, max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('show_first', models.IntegerField(default=1)),
                ('date', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
