# Generated by Django 4.2.4 on 2024-04-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_portfoliomodel_experience_portfoliomodel_iam'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
    ]
