# Generated by Django 4.2.4 on 2024-04-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_portfoliomodel_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencemodel',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
