# Generated by Django 4.2.4 on 2024-04-03 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_experiencemodel_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.CharField(blank=True, max_length=2000)),
                ('fullname', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=2000)),
                ('show_first', models.IntegerField(default=1)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
