# Generated by Django 4.2.4 on 2024-04-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagetoolsmodel',
            name='proficiency',
            field=models.FloatField(default=90),
        ),
    ]
